### ISSUE TITLE
ABM Registrar Consumibles

### ISSUE THREAD

**Issue by matiasdodero** [FedeRoma/GDD2018#1]
Tira error al abrir esa funcionalidad

![imagen](https://user-images.githubusercontent.com/11743774/42425719-2fb0f6a6-82f7-11e8-96d5-6f30f94a89e5.png)

![imagen](https://user-images.githubusercontent.com/11743774/42425711-19f074a4-82f7-11e8-946d-ccdc3aec1903.png)

**Comment by lithium21** [comment]
En la misma captura está la respuesta al problema!!
En el script inicial, cuando se carga la Tabla de Funcionalidades, tuvimos un error de tipeo y pusimos "Registar Consumibles", por eos el case no entra en esa opción!
