### ISSUE TITLE
ABM Hotel

### ISSUE THREAD

**Issue by ghost** [FedeRoma/GDD2018#11]
- Al dar de alta un hotel no se le asignan los regimenes seleccionados
- Si modifico un hotel, el mismo se deshabilita sin importar que esté modificando.
- Si modifico un hotel y le quito algún regimen, esto no surte efecto. Tener en cuenta que para quitar regimenes también hay que validar lo del enunciado "Consideración importante: el Hotel puede tener diferentes regímenes de estadía para ofrecer a sus huéspedes, por lo tanto deberá tenerse en cuenta que si se quita algún tipo de régimen, no deben haber reservas tomadas y tampoco huéspedes alojados bajo dicho régimen para que pueda llevarse a cabo la modificación. En caso de haber reservas o huéspedes alojados se deberá informar la imposibilidad de quitar el régimen e informarlo debidamente al usuario. "

**Comment by FedeRoma** [comment]
Arreglado esto:
Si modifico un hotel, el mismo se deshabilita sin importar que esté modificando.

**Comment by ghost** [comment]
@FedeRoma Ok lo de que no se deshabilite al modificar el hotel.

**Comment by ghost** [comment]
Sigue fallando este:

- Al modifica y quitar o agregar regimenes, esto no surte efecto. Tener en cuenta que para quitar regimenes también hay que validar lo del enunciado "Consideración importante: el Hotel puede tener diferentes regímenes de estadía para ofrecer a sus huéspedes, por lo tanto deberá tenerse en cuenta que si se quita algún tipo de régimen, no deben haber reservas tomadas y tampoco huéspedes alojados bajo dicho régimen para que pueda llevarse a cabo la modificación. En caso de haber reservas o huéspedes alojados se deberá informar la imposibilidad de quitar el régimen e informarlo debidamente al usuario. "

**Comment by ghost** [comment]
- No olvidarse de chequear que en la modif el hotel no se quede sin regimenes porque rompe la app

**Comment by ghost** [comment]
pasa a otro issue esto
