### ISSUE TITLE
AbmHotel - AltaHotel

### ISSUE THREAD

**Issue by lithium21** [FedeRoma/GDD2018#12]
Al limpiar los datos, no limpia la parte de Regímenes

**Comment by ghost** [comment]
@lithium21 Esto me sigue fallando. Para validarlo, entiendo que te referís a que al apretar en "limpiar datos" se deberían salir los regimenes ya seleccionados, pero no pasa:
![image](https://user-images.githubusercontent.com/11934209/42720545-2986940a-86ff-11e8-82e0-d08d6bc28f51.png)

**Comment by ghost** [comment]
Cerrado !
