### ISSUE TITLE
Checkin

### ISSUE THREAD

**Issue by ghost** [FedeRoma/GDD2018#15]
Se rompe la aplicación al intentar realizar el checkin. Para probarlo, editar desde el SQL:

update en_casa_andaba.reservas
set res_estados_id = 1, res_inicio = getdate(), res_fin=getdate()+5
where res_id = 13068

Para hacer el registro de estadía se debe seleccionar el hotel 1 (Avenida Cordoba 10482) ya que solo deberíamos poder hacer registros de estadías que sean de ese hotel (de lo contrario debería salir un cartel de que no existe esa reserva para ese hotel)

**Comment by lithium21** [comment]
Problema con el SP, issue#19

**Comment by ghost** [comment]
Ejecutar en SQL esto:

delete from en_casa_andaba.Clientes_Estadias where cye_est_res_id = 13068
delete from en_casa_andaba.items_facturas where iyf_est_res_id = 13068
delete from en_casa_andaba.facturas where fac_est_res_id = 13068
delete from en_casa_andaba.estadias where est_res_id = 13068
update en_casa_andaba.reservas
set res_estados_id = 1, res_inicio = getdate(), res_fin=getdate()+5
where res_id = 13068

Después de esto, podés hacer el checkin de la reserva 13068 en el hotel 1
