### ISSUE TITLE
ABM Cliente - Modificacion

### ISSUE THREAD

**Issue by ghost** [FedeRoma/GDD2018#16]
Se pisan los registros al editar y usar un mismo número de documento (con distinto tipo).

Ejemplo para probar:

Agarrar un user A:
Datos personales: Juan Fernandez bla bla bla
Tipo documento: Pasaporte
Numero de documento: 1234

Agarrar un user B:
Datos personales: Pedro Rodriguez bla bla bla
Tipo documento: Pasaporte
Numero de documento 5678

Edito el user B y le cambio el numero 5678 por 1234 y el tipo de Documento de Pasaporte a DNI. Cuando hago click en guardar, el registro en lugar de llamarse Pedro Rodriguez se llama Juan Fernandez (como que pisa el registro con el que tiene el mismo numero de doc).

**Comment by lithium21** [comment]
me suena a algún error en el SP modificarCliente

**Comment by ghost** [comment]
Definimos impedir el cambio de tipo y numero de doc dado que es nuestra PK y si lo cambiamos, rompemos toda la estructura de las tablas, reservas, estadias... Lo agregamos en la estrategia.

Este issue en definitiva tiene que lograr que los campos se grisen para no ser editables.
