### ISSUE TITLE
ABM Hotel - Baja

### ISSUE THREAD

**Issue by ghost** [FedeRoma/GDD2018#18]
No sucede nada cuando uno da click en "aceptar", sin importar que hotel intente dar de baja.

Dejo anotado por acá, que una vez que funcione la baja, para validar que no permita dar de baja hoteles con reservas activas, debemos modificar lo siguiente en SQL:

update en_casa_andaba.reservas
set res_estados_id = 1, res_inicio = getdate()+1
where res_id = 13068

Y debemos intentar dar de baja el hotel 1 (Avenida Cordoba 10482), el cual no debería permitir la baja por tener reservas activas.

**Comment by lithium21** [comment]
insert into EN_CASA_ANDABA.BajasHotel (baj_hot_id, baj_fecha_inicio, baj_fecha_fin, baj_motivo) values ()

probar este insert con algunos valores a ver que pasa

**Comment by ghost** [comment]
Dejo un ejemplo que anda:

insert into EN_CASA_ANDABA.BajasHotel (baj_hot_id, baj_fecha_inicio, baj_fecha_fin, baj_motivo) values (1,getdate(),getdate()+5,'test')

**Comment by ghost** [comment]
Por el momento, sigue fallando. Dice que tiene reservas activas cuando no las tiene (probé con una fecha de baja de 2020 que no tiene reservas)

**Comment by ghost** [comment]
Cerrado
