### ISSUE TITLE
SP [altaCheckInEstadia] falla 

### ISSUE THREAD

**Issue by FedeRoma** [FedeRoma/GDD2018#19]
No puede hacer el insert a estadia ya que existe otro id igual. (SIEMPRE VA A PASAR)

**Comment by ghost** [comment]
Esto lo pensamos mal, porque usamos datos de la maestra en lugar de generar una reserva nueva. Para poder usar de la maestra, hay que hacer mierda la estadia y ahi si funciona. Para romper la estadia, ejecutar en SQL:

delete from en_casa_andaba.Clientes_Estadias where cye_est_res_id = 13068
delete from en_casa_andaba.items_facturas where iyf_est_res_id = 13068
delete from en_casa_andaba.facturas where fac_est_res_id = 13068
delete from en_casa_andaba.estadias where est_res_id = 13068
update en_casa_andaba.reservas
set res_estados_id = 1, res_inicio = getdate(), res_fin=getdate()+5
where res_id = 13068

Después de esto, podés hacer el checkin de la reserva 13068 en el hotel 1
