### ISSUE TITLE
Checkin

### ISSUE THREAD

**Issue by ghost** [FedeRoma/GDD2018#26]
Para probar el checkin primero ejecutar en SQL:
delete from en_casa_andaba.Clientes_Estadias where cye_est_res_id = 13068
delete from en_casa_andaba.items_facturas where iyf_est_res_id = 13068
delete from en_casa_andaba.facturas where fac_est_res_id = 13068
delete from en_casa_andaba.estadias where est_res_id = 13068
update en_casa_andaba.reservas
set res_estados_id = 1, res_inicio = getdate(), res_fin=getdate()+5
where res_id = 13068

El error que se está dando es que al parecer el SP de altacheckinestadia está devolviendo 1 en lugar de devolver el ID de la estadia (el SP funciona, pero retorna 1 en lugar del id de estadia). A su vez, en el siguiente SP que se ejecuta (altafactura) se pasa este ID de estadia 1 erroneo y entonces no se genera la factura bien.

Por otro lado, el otro error es que el SP altafactura tiene un error propio y es que inserta en el campo mediopagoid un 0, cuando los IDs son 1 o 2. Mi recomendación es quitar ese campo mediopago del SP, porque no lo tenemos hasta ese momento, no es algo que el cliente ya tenga elegido.

**Comment by lithium21** [comment]
Hay algún problema para dar de alta la factura y para mí tiene que ver con la PK que se autoincrementa.

**Comment by maxicardozo** [comment]
Esto está ok a medias, queda resolver el tema Generar factura en el issue 32

**Comment by ghost** [comment]
Por ahora esto sigue fallando entonces.

**Comment by ghost** [comment]
Hay que modificar un dato facil para que no falle la factura:

- Antes: idFactura = Index.BD.consultaGetInt("exec EN_CASA_ANDABA.altaFactura " + idEstadia.ToString() + ", 0, '" + DateTime.Today.ToString("yyyyMMdd HH:mm:ss") + "'");
- Despues: idFactura = Index.BD.consultaGetInt("exec EN_CASA_ANDABA.altaFactura " + idEstadia.ToString() + ", 1, '" + DateTime.Today.ToString("yyyyMMdd HH:mm:ss") + "'");

Básicamente se cambia el 0 por un 1.

- Por otro lado, si se cambia eso, igualmente el siguiente paso explota con:
![image](https://user-images.githubusercontent.com/11934209/42718140-c135836a-86dc-11e8-9918-2b3807a19a56.png)

**Comment by ghost** [comment]
@FedeRoma  Lo que rompe esta en uno de estos iguales.
            qry = Index.BD.consultaGetPuntero("select sum(TH.tip_personas) from EN_CASA_ANDABA.Reservas_Habitaciones RH, EN_CASA_ANDABA.Habitaciones H, EN_CASA_ANDABA.TiposHabitaciones TH where RH.ryh_hab_id = H.hab_id and TH.tip_id = H.hab_tip_id and RH.ryh_res_id = " + reservaID);

**Comment by ghost** [comment]
Sigo este bug en otro issue
