### ISSUE TITLE
Checkout

### ISSUE THREAD

**Issue by ghost** [FedeRoma/GDD2018#27]
Para arrancar hay que ejecutar en SQL:
UPDATE en_casa_andaba.estadias
set est_checkout = null

- Falta el icono de selec.ico
- Al intentar elegir una estadia se rompe la app con el siguiente error:
![image](https://user-images.githubusercontent.com/11934209/42608960-bfe53564-8560-11e8-9159-6f2d4a8aa7bf.png)

**Comment by ghost** [comment]
@lithium21 Para que funcione, hay que modificar el SP altaCheckOutEstadia y colocar antes del commit tran tAltaCheckoutEstadia lo siguiente:

				set @respuesta = 1
				select @respuesta as respuesta

- Y resta otro problema, que es igual al issue 24, y es que podés hacer checkouts de cualquier estadía de cualquier hotel estando logueado en 1 solo.

**Comment by lithium21** [comment]
solucionado el SP.
Y yo sólo veo las habitaciones del Hotel en el que estoy logueado en el listado...

**Comment by ghost** [comment]
@lithium21 ¿Seguro?

Yo siempre pruebo todo con el hotel 1, y tengo las siguientes estadias a realizar checkout (antes claro, corrí el update en todas las estadias para ponerles null en el checkout):
![image](https://user-images.githubusercontent.com/11934209/42704589-d4e262a6-86a6-11e8-8557-36b58f08adad.png)

Me fijé en reservas_habitaciones para ver si la reserva es del hotel 1 y me dice 13, y con otras pasa lo mismo: select * from en_casa_andaba.reservas_habitaciones where ryh_res_id = 10067
