### ISSUE TITLE
modificar SP altaUsuario para que hashee las contrasenas

### ISSUE THREAD

**Issue by FedeRoma** [FedeRoma/GDD2018#30]
Revisar y agregar la funcion HASHBYTES a los campos clave

hashbytes('SHA2_256',PASSWORD);

**Comment by ghost** [comment]
Esto no estaría pasando.

El SP hashea bien: exec EN_CASA_ANDABA.altaUsuario 'Administrador General','Avenida Córdoba',10482,'admin2','12345678','admin','admin','admin@en_casa_andaba.com','4000-0000','Pasaporte',12345678,'2018-01-01','admin'

Y si probás un alta de usuario desde C se hashea en la tabla de SQL y te deja loguearte bien.
