### ISSUE TITLE
Checkout - Generar factura

### ISSUE THREAD

**Issue by ghost** [FedeRoma/GDD2018#32]
El checkout se genera correctamente en la tabla estadías, pero el conflicto viene en el siguiente paso que es la generación de la factura.

- Si ya existe factura (siempre va a existir factura en este paso, dado que la creamos en el checkin para poder asociar los consumibles) me dice que no puede facturar algo facturado. Revisé el código y me parece que el conflicto viene en:
            qry = Index.BD.consultaGetPuntero("select fac_id from EN_CASA_ANDABA.Facturas where fac_est_res_id = "+ estadia.Text);
            if (qry.Read())
            {
                alerta = alerta + "La estadía " + estadia.Text + " ya fue facturada\nFactura Nro.: " + qry.GetInt32(0).ToString() + "\n";
                inconsistencias = true;
            }
Mi recomendación es que saques esta validación chota, ya que el sistema no te permite intentar facturar sin hacer antes un checkout, y el checkout ya te va a filtrar a los clientes que lo hayan realizado, no te deja hacer checkout de algo que ya se hizo.

- Ahora, yo agarré para probar esto sin cambiar nada y borré de SQL mi factura, para intentar facturar igual. El tema es que cuando intento avanzar, me topo con el sig error:

![image](https://user-images.githubusercontent.com/11934209/42698759-39730e94-8695-11e8-953e-168c0b0278cf.png)

**Comment by maxicardozo** [comment]
Excelente!

**Comment by ghost** [comment]
Cerrado bien!
