### ISSUE TITLE
Registrar Consumibles

### ISSUE THREAD

**Issue by ghost** [FedeRoma/GDD2018#33]
- No funciona el botón atrás ni el botón limpiar datos
- Cuando cargo consumibles y doy click en aceptar falla con el siguiente error:
![image](https://user-images.githubusercontent.com/11934209/42699199-6b50c162-8696-11e8-95b2-91e0327cdc7c.png)

**Comment by ghost** [comment]
Issue en el archivo ListadoEstadias.cs. Modificar:

- Antes: tablaEstadias = Index.BD.consultaGetTabla("select distinct CE.cye_cye_id IdEstadia, CE. cye_hab_id IdHabitacion, H.hab_numero NUMERO, H.hab_piso PISO, R.res_reg_id Regimen from EN_CASA_ANDABA.Estadias E, EN_CASA_ANDABA.Clientes_Estadias CE, EN_CASA_ANDABA.Habitaciones H,EN_CASA_ANDABA.Reservas R  where CE. cye_est_res_id = E. est_res_id and CE. cye_hab_id=H.hab_id and (cye_cye_id)is not NULL and CE.cye_hab_hot_id=H.hab_hot_id and est_res_id = R.res_id and H.hab_hot_id =" + Index.hotel);

- Despues: tablaEstadias = Index.BD.consultaGetTabla("select distinct CE.cye_est_res_id IdEstadia, CE. cye_hab_id IdHabitacion, H.hab_numero NUMERO, H.hab_piso PISO, R.res_reg_id Regimen from EN_CASA_ANDABA.Estadias E, EN_CASA_ANDABA.Clientes_Estadias CE, EN_CASA_ANDABA.Habitaciones H,EN_CASA_ANDABA.Reservas R  where CE. cye_est_res_id = E. est_res_id and CE. cye_hab_id=H.hab_id and (cye_cye_id)is not NULL and CE.cye_hab_hot_id=H.hab_hot_id and est_res_id = R.res_id and H.hab_hot_id =" + Index.hotel);

Lo que modifiqué es que estabamos trayendo cualquier cosa en lugar del ID de la estadia. Ahora puse que traiga el ID de estadia: CE.cye_est_res_id

**Comment by ghost** [comment]
Ahora que pude ejecutar todo, vi que hay que modificar 2 cosas en un SP (registrarConsumibleEstadia) y ya queda todo andando.

- Antes:  if( exists(select iyf_id from EN_CASA_ANDABA.Items_Facturas where iyf_fac_id = @factu))
- Despues: if( exists(select iyf_id from EN_CASA_ANDABA.Items_Facturas where iyf_fac_id = @factu and iyf_con_id = @cons))

- Antes: set @item = (select iyf_id from EN_CASA_ANDABA.Items_Facturas where  iyf_fac_id = @factu)
- despues: set @item = (select iyf_id from EN_CASA_ANDABA.Items_Facturas where  iyf_fac_id = @factu and iyf_con_id = @cons)

**Comment by matiasdodero** [comment]
checking

**Comment by ghost** [comment]
Cerrado
