### ISSUE TITLE
Modificar Reserva

### ISSUE THREAD

**Issue by ghost** [FedeRoma/GDD2018#34]
- Se pueden modificar reservas en estado "con ingreso" o "canceladas" por cualquier motivo.
- Si selecciono una habitación disponible con doble click, da error:
![image](https://user-images.githubusercontent.com/11934209/42700637-b78c14d8-869a-11e8-80b7-c1279729f76b.png)
- Si busco una habitación da error:
![image](https://user-images.githubusercontent.com/11934209/42700683-dd92a73c-869a-11e8-8267-a7c4268c77bb.png)

**Comment by FedeRoma** [comment]
Agregar las reservas que si se pueden modificar

**Comment by FedeRoma** [comment]
Solo se pueden modificar
1	Reserva CORRECTA
2	Reserva MODIFICADA

**Comment by ghost** [comment]
Al intentar buscar habitaciones en "Generar reserva" falla con el siguiente error:
![image](https://user-images.githubusercontent.com/11934209/42719820-92213bb2-86f2-11e8-9a6d-c8d6112b42d4.png)


Abajo se ve que el problema es uno de los datos que se pasa al procedure.

**Comment by ghost** [comment]
Ahora se pueden buscar habitaciones pero no se pueden elegir:
![image](https://user-images.githubusercontent.com/11934209/42720335-b89cd324-86fb-11e8-9455-c7d16b1bdc7f.png)

**Comment by ghost** [comment]
Al intentar agregar una habitacion con el icono de agregar, falla:
![image](https://user-images.githubusercontent.com/11934209/42720690-9ce5ef4c-8702-11e8-9095-70d735b6d3c5.png)

**Comment by ghost** [comment]
Lo sigo en otro issue aparte
