### ISSUE TITLE
SP modificacionFactura

### ISSUE THREAD

**Issue by ghost** [FedeRoma/GDD2018#35]
- Modificar el valor @deuda tanto para cuando el regimen es 4 como para cuando es distinto de 4 (2 cambios iguales):

- Antes del cambio: @deuda = (select est_precio from EN_CASA_ANDABA.Estadias where est_res_id = @estadiaId)

- Despues del cambio:  @deuda = (select est_precio from EN_CASA_ANDABA.Estadias where est_res_id = @estadiaId)*(select est_cant_noches from EN_CASA_ANDABA.Estadias where est_res_id = @estadiaId)

**Comment by lithium21** [comment]
Corregido, probar por favor

**Comment by ghost** [comment]
Joya.
