### ISSUE TITLE
AbmHotel - Alta Hotel

### ISSUE THREAD

**Issue by lithium21** [FedeRoma/GDD2018#4]
Al dar de alta, ese hotel debería asignarse automáticamente al user que lo da de alta y no pasa

**Comment by ghost** [comment]
No acepta hoteles con nombre de más de 1 palabra (ver la query tirada a SQL donde falla por el espacio en la captura). Creo que se podría resolver enviando esa data entre ' '

![image](https://user-images.githubusercontent.com/11934209/42719709-c539e0aa-86f0-11e8-8a2c-702981e11e08.png)

**Comment by ghost** [comment]
Excelente.
