### ISSUE TITLE
AbmHabitacion - BajaHabitacion

### ISSUE THREAD

**Issue by lithium21** [FedeRoma/GDD2018#6]
Chequear antes de dar de baja, que la habitación no tenga reservas.
Hay una función "estaReservadaHabitacion" que puede servir

**Comment by FedeRoma** [comment]
Commit, testearlo y cerrar

**Comment by FedeRoma** [comment]
Dejo querys para testear
	select EN_CASA_ANDABA.estaReservadaHabitacion('2018-07-03','2018-07-11',999)
	select EN_CASA_ANDABA.estaReservadaHabitacion('12/07/2018 0:00:00','4000-07-11',3)

select * from EN_CASA_ANDABA.Reservas, EN_CASA_ANDABA.Reservas_Habitaciones where ryh_hab_id = 113 and ryh_res_id = res_id

**Comment by ghost** [comment]
@FedeRoma No me deja dar de baja ninguna habitación. Para probarlo busque habitaciones que no hayan tenido nunca una reserva (del hotel 1):

select ryh_hab_id from en_casa_andaba.reservas_habitaciones where ryh_hab_hot_id = 1 group by ryh_hab_id order by ryh_hab_id

Por ejemplo, las habitaciones 0, 4, 6, 8, 10 etc nunca tuvieron una reserva. Intenté darles de baja y me dice que tienen reservas.

----
Opinión:
Creo que hay que cambiar el procedure (hoy tiene muchos ifs). Me parece que estaba diseñado para que cuando des la baja elijas una fecha de inicio y fin de la baja de la habitacion y se chequee, pero como la baja es manual y no es por fechas, creo que se puede simplificar el procedure para que no sea tan complejo.
Para esto, me parece que sería más facil que el procedure mire si hay reservas activas (SI NO LE PIFIO  bastaría validar (res_inicio >= hoy OR res_fin >= a hoy) y revisar obviamente que la reserva no haya sido cancelada por algún motivo esa reserva.

Y ahí podrías borrar el campo "hasta" del procedure que está al pedo.

**Comment by ghost** [comment]
@FedeRoma Me retracto! lo probé mal, me confundí id de habitación con número. Ahí probé borrando registros de reservas_habitaciones y al menos las que no tienen registros funcan:

delete from en_casa_andaba.reservas_habitaciones where ryh_hab_id = 1

y luego di de baja la habitacion numero 2 piso 6 vista N (que es la del id 1)

Ahora voy a probar agregar registros con fechas raras a ver si lo valida bien.

**Comment by ghost** [comment]
@FedeRoma LISTO probé todas las chances y anda. Si es una reserva vieja la que esta en la tabla, deja dar de baja, si son reservas activas se anulan.

Caso cerrado!
