### ISSUE TITLE
ABM Habitacion

### ISSUE THREAD

**Issue by ghost** [FedeRoma/GDD2018#7]
- El enunciado dice que no se debe poder modificar el tipo de habitación, y el "modificación" lo permite. Creo que si permitimos modificar el tipo nos afecta en el tema de los precios de las habitaciones reservadas y eso, con lo cual yo no lo pondría como campo editable.
- El enunciado dice que no puede haber 2 habitaciones con el mismo número de habitación, y el sistema lo permite.
- El campo "Vista" es un char en la tabla habitaciones, y de la maestra sale que las opciones son S o N (se supone que las alternativas son interior o exterior) con lo cual creo que debería cambiarse el nombre de "Vista" por "Exterior" por ejemplo, y que se pueda completar solo con S o N como si fuese un SI o NO a que sea exterior.

**Comment by lithium21** [comment]
- Se cambia el combobox para seleccionar el tipo de habitación por un textBox que no puede ser editado para evitar que se modifique.
- Se chequea que el número de habitación no esté ya registrado en dicho Hotel.
- Sobre el campo "Vista", le puse ese nombre porque supuse que era Vista (Si/No), Vista Si, sería exterior y Vista No sería interior.

**Comment by ghost** [comment]
@lithium21 No, guarda, no me refería solo al nombre del campo, sino al hecho de que el campo es de texto libre y debería ser un tabulado que ofrezca dos opciones S o N. Fijate que el campo tiene para poner cualquier texto.

**Comment by ghost** [comment]
Ya lo agregue en el issue 23
