### ISSUE TITLE
ABM Clientes - Alta

### ISSUE THREAD

**Issue by ghost** [FedeRoma/GDD2018#9]
- Si doy de alta un cliente con tipo y número de documento repetido, el sistema me da el OK (aquí el error) pero internamente se valida correctamente y no se crea ese cliente. Lo mismo sucede cuando editás un cliente y le ponés un tipo y número repetido.

**Comment by lithium21** [comment]
Resuelto!
En el caso del alta se incluye el chequeo en la validación de datos.
En el caso de la modificacion, se extiende un poco más el chequeo para abarcar el caso de que en la modificación se mantengan estos datos, sino no permitiría hacer un update sobre el registro manteniendo el Tipo y Nro de documento originales.

**Comment by ghost** [comment]
Perfecto esto. Lo dejo asentado para quedarme tranquilo
